import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
	return twMerge(clsx(inputs));
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type WithoutChild<T> = T extends { child?: any } ? Omit<T, 'child'> : T;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type WithoutChildren<T> = T extends { children?: any } ? Omit<T, 'children'> : T;
export type WithoutChildrenOrChild<T> = WithoutChildren<WithoutChild<T>>;
export type WithElementRef<T, U extends HTMLElement = HTMLElement> = T & { ref?: U | null };

/**
 * Filters out raw markdown recipe text, tables, ingredient lists, and step lists
 * that might be generated by the AI alongside a tool call.
 */
export function cleanRecipeText(text: string | null | undefined): string {
	if (!text) return '';

	// If text contains common markdown recipe delimiters/headers/tables, cut off at that point
	let cleaned = text.split(/---|###|\n\s*\||\bZutaten\b|\bSchritte\b/i)[0];

	cleaned = cleaned.trim();

	// If the resulting text is just markdown formatting symbols or empty, return empty string
	if (/^[#*\-\s|]+$/.test(cleaned)) {
		return '';
	}

	return cleaned;
}
